version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: hyh-backend/Dockerfile
    env_file:
      - hyh-backend/.env # Usa variables reales en despliegue o mapea variables en tu plataforma
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000}
    environment:
      - NODE_ENV=production
      # Importante: las rutas API del servidor Next deben llamar al backend por red interna
      - NEXT_PUBLIC_API_URL=http://backend:4000
      # Permite cookies no seguras (HTTP) cuando no hay HTTPS/domino
      - COOKIE_SECURE=false
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

# Opcional: si prefieres DB local, añade un servicio postgres aquí y ajusta DATABASE_URL
