services:
  - type: web
    name: hyh-backend
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: hyh-backend/Dockerfile
    dockerContext: hyh-backend
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hyh-postgres
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: hyh-postgres
          property: connectionString
      - key: CORS_ORIGIN
        value: https://tu-frontend.com
      # Opcionales: Configúralos en el dashboard o edita este archivo
      # - key: CLOUDINARY_CLOUD_NAME
      #   value: ""
      # - key: CLOUDINARY_API_KEY
      #   value: ""
      # - key: CLOUDINARY_API_SECRET
      #   value: ""
      # - key: CLOUDINARY_FOLDER
      #   value: hyh-shop
      # - key: WOMPI_ENV
      #   value: sandbox
      # - key: WOMPI_PUBLIC_KEY
      #   value: ""
      # - key: WOMPI_PRIVATE_KEY
      #   value: ""
      # - key: WOMPI_INTEGRITY_KEY
      #   value: ""
      # - key: FRONTEND_URL
      #   value: https://tu-frontend.com

databases:
  - name: hyh-postgres
    plan: starter
    databaseName: hyhdb
    user: hyh
    postgresMajorVersion: 15

